## File Handling

In [2]:
f=open("lauha.txt", "r")
print(f.read())

Hallo, nama saya Lauha Kurnia Safira dengan NIM 200601110056.
Saya adalah mahasiswa jurusan Matematika di UIN MALIKI MALANG.
Senang bisa mengikuti kelas Praktikum Pemograman Komputer 1 setiap hari Kamis pagi.


In [3]:
f=open("lauha.txt", "r")
print(f.read(20))

Hallo, nama saya Lau


In [4]:
f=open("lauha.txt", "a")
f.write("Now the file has more content!")
f.close()

#open and read the file after the appending:
f=open("lauha.txt", "r")
print(f.read())

Hallo, nama saya Lauha Kurnia Safira dengan NIM 200601110056.
Saya adalah mahasiswa jurusan Matematika di UIN MALIKI MALANG.
Senang bisa mengikuti kelas Praktikum Pemograman Komputer 1 setiap hari Kamis pagi.Now the file has more content!


## CHAPTER 5
### Praktikum 9: PendahuluanNumPy
#### 5.1 Pendahuluan
Topik utama dari NumPy adalah array multidimensi yang diindeks oleh tuple atau pasangan bilangan bulat positif. Dalam NumPy dimensi disebut sebagai axis, dan banyaknya axis disebut rank. Sebagai contoh, koordinat sebuah titik diruang 3D dinyatakan sebagai [1,2,1] yang merupakan sebuah array dengan rank 1 karena terdiri dari satu axis. Sedangkan panjang axis tersebut adalah 3. Pada contoh berikut, array-nya mempunyai rank 2. Axis pertama panjangnya 2, dan axis kedua panjangnya 3

In [ ]:
[[ 1., 0., 0.],
[ 0., 1., 2.]]

array NumPy disebut sebagai ndarray , atau dikenal juga dengan sebutan array. Catat bahwa numpy.array tidak sama dengan array Standard Python array.array, yang hanya bisa digunakan untuk array 
satu dimensi dan dengan fitur yang lebih sedikit. Atribut yang paling penting dari ndarray adalah:
ndarray.ndim banyaknya axis atau dimensi dari array. Di Python, banyaknya dimensi disebut sebagai rank.
ndarray.shape dimensi dari array. Ini adalah pasangan bilangan bulat yang menunjukkan ukuran array di setiap dimensi. Untuk matriks dengan n baris dan m kolom, bentuknya adalah (n, m). Panjang dari pasangan shape adalah rank, atau jumlah dimensi, ndim.
ndarray.size jumlah elemen dari array. Ini sama dengan perkalian elemen dari shape.
ndarray.dtype sebuah objek yang menggambarkan jenis elemen dalam array. Seseorang dapat membuat atau menentukan jenis dtype menggunakan jenis Python standar. Selain itu NumPy menyediakan jenisnya sendiri. numpy.int32, numpy.int16, dan numpy.float64 adalah beberapa contohnya.
ndarray.itemsize ukurandalambytedarisetiapelemenarray. Sebagai contoh, sebuah array dari elemen tipe float64 memiliki itemsize 8 (= 64/8), sedangkan satu dari tipe complex32 memiliki itemsize 4 (= 32/8). Ini sama dengan ndarray.dtype.itemsize.
ndarray.data buffer yang mengandung elemen sebenarnya dari array. Biasanya, kita tidak perlu menggunakan atribut ini karena kitaakan mengakses elemen dalam array menggunakan fasilitas pengindeksan.
Contoh:

In [9]:
import numpy as np
a=np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [10]:
a.shape

(3, 5)

In [11]:
a.ndim

2

In [12]:
a.dtype.name

'int32'

In [13]:
a.itemsize

4

In [14]:
a.size

15

In [15]:
type(a)

numpy.ndarray

In [16]:
b=np.array([6,7,8])
b

array([6, 7, 8])

In [17]:
type(b)

numpy.ndarray

#### 5.2 Membuat Array
Ada beberapa cara untuk membuat array. Misalnya, Anda dapat 
membuat array dari list Python biasa atau pasangan menggunakan 
fungsi array. Tipe array yang dihasilkan disimpulkan dari tipe elemen 
dalam array.


In [18]:
import numpy as np
a=np.array([2,3,4])
a

array([2, 3, 4])

In [19]:
a.dtype

dtype('int32')

In [20]:
b=np.array([1.2,3.5,5.1])
b.dtype

dtype('float64')

Kesalahan yang sering terjadi dalam pembuatan array diantaranya adalah:

In [ ]:
a=np.array(1,2,3,4) #WRONG
a=np.array([1,2,3,4]) #RIGHT

array mengubah barisan dari sebuah barisan menjadi array dua dimensi, barisan dari barisan sebuah barisan menjadi array tiga dimensi, dan seterusnya.

In [21]:
b=np.array([(1.5,2,3),(4,5,6)])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

Jenis array juga dapat secara eksplisit ditentukan pada saat pembuatan:

In [22]:
c = np. array ( [ [1 ,2] , [3 ,4] ] , dtype = complex )
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

Seringkali, elemen dari sebuah array pada awalnya tidak diketahui, 
namun ukurannya diketahui. Oleh karena itu, NumPy menawarkan 
beberapa fungsi untuk membuat array yang memuat nilai awal. Hal 
tersebut dapat meminimalkan pertumbuhan memori yang diperlukan 
array , sebagai operasi yang dianggap mahal.
Fungsi zeros menciptakan sebuah array yang berisi angka nol, fungsi 
ones yang menciptakan array yang berisi angka satu, dan fungsi empty 
men ciptakan array yang isinya acak dan bergantung pada keadaan 
memori. Secara default, dtype dari array yang dibuat adalah float64.


In [23]:
np. zeros ( (3 ,4) )

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [24]:
np. ones ( (2 ,3 ,4) , dtype =np. int16 ) # dtype can also be specified

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [25]:
np. empty ( (2 ,3) ) # uninitialized , output may vary

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

Untuk membuat barisan angka, NumPy menyediakan fungsi yang mirip dengan range yang outputnya berupa array dan bukan berupa list .

In [26]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [27]:
np.arange(0,2,0.3) #it accepts float arguments

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

ika arange digunakan dengan argumen floating point, biasanya sulit memprediksi jumlah elemen yang diperoleh, karena presisi floating point yang terbatas. Untuk itu, lebih baik menggunakan fungsi linspace yang dapat menerima masukan berapa jumlah elemen yang kita inginkan:

In [28]:
from numpy import pi
np.linspace(0.2,9) #9 numbers from 0 to 2

array([0.2       , 0.37959184, 0.55918367, 0.73877551, 0.91836735,
       1.09795918, 1.27755102, 1.45714286, 1.63673469, 1.81632653,
       1.99591837, 2.1755102 , 2.35510204, 2.53469388, 2.71428571,
       2.89387755, 3.07346939, 3.25306122, 3.43265306, 3.6122449 ,
       3.79183673, 3.97142857, 4.15102041, 4.33061224, 4.51020408,
       4.68979592, 4.86938776, 5.04897959, 5.22857143, 5.40816327,
       5.5877551 , 5.76734694, 5.94693878, 6.12653061, 6.30612245,
       6.48571429, 6.66530612, 6.84489796, 7.0244898 , 7.20408163,
       7.38367347, 7.56326531, 7.74285714, 7.92244898, 8.10204082,
       8.28163265, 8.46122449, 8.64081633, 8.82040816, 9.        ])

In [29]:
x=np.linspace(0,2*pi,100) #useful to evaluate function at lots of points

In [30]:
f=np.sin(x)

#### 5.3 Menampilkan Array
Saat kita menampilkan array , NumPy menampilkannya dengan cara yang mirip dengan daftar bersarang, namun dengan tata letak berikut: • axis terakhir dicetak dari kiri ke kanan, • yang kedua sampai yang terakhir dicetak dari atas ke bawah, • Sisanya juga dicetak dari atas ke bawah, dengan masingmasing potongan dipisahkan oleh sebuah baris kosong. array satu dimensi dicetak sebagai baris, array dua dimensi sebagai matriks dan tridimensionals sebagai daftar matriks.

In [31]:
a = np.arange(6) #1d array
print(a)

[0 1 2 3 4 5]


In [32]:
b = np.arange(12).reshape(4,3) # 2d array
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


Jika a rray terlalu besar untuk ditampilkan, NumPy secara otomatis memotong bagian tengah array dan hanya mencetak ujung-ujungnya:

In [33]:
print(np.arange(10000))

[   0    1    2 ... 9997 9998 9999]


In [34]:
print(np.arange(10000).reshape(100,100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


Untuk memaksa NumPy mencetak seluruh bagian array , kita dapat mengubah opsi print menggunakan set_printoptions .

np.set_printoptions(threshold=’nan’)